export const CARRIER_MAP: Record<string, { carrier: string; network: string }> = {
  'US': { carrier: 'AT&T / T-Mobile', network: '5G' },
  'GB': { carrier: 'EE / 3', network: '5G' },
  'CA': { carrier: 'Freedom / Telus', network: '5G' },
  'JP': { carrier: 'KDDI / SoftBank', network: '4G/5G' },
  'MX': { carrier: 'Movistar / AT&T', network: '4G' },
  'DE': { carrier: 'O2 / Vodafone', network: '5G' },
  'FR': { carrier: 'Bouygues / Orange', network: '5G' },
  'CH': { carrier: 'Sunrise / Salt', network: '5G' },
  'TH': { carrier: 'AIS / dtac / True', network: '4G/5G' },
  'MY': { carrier: 'Celcom / Digi / Maxis', network: '5G' },
  'PH': { carrier: 'Globe / Smart', network: '5G' },
  'AU': { carrier: 'Optus', network: '5G' },
  'KR': { carrier: 'SK / LG U+ / KT', network: '5G' },
  'SG': { carrier: 'SingTel / StarHub', network: '5G' },
  'CN': { carrier: 'China Telecom / Unicom', network: '5G' },
  'IT': { carrier: 'Windtre / Vodafone', network: '5G' },
  'HK': { carrier: 'HKT / CSL', network: '5G' },
  'TW': { carrier: 'Chunghwa / FarEasTone', network: '5G' },
  'ID': { carrier: 'Telkomsel / Hutchison', network: '4G/5G' },
  'VN': { carrier: 'MobiFone / Viettel', network: '4G' },
  'NZ': { carrier: 'Spark / Vodafone', network: '5G' },
  'BE': { carrier: 'Proximus / BASE', network: '5G' },
  'NL': { carrier: 'KPN / Vodafone', network: '5G' },
  'SE': { carrier: 'Telenor / Telia', network: '5G' },
  'NO': { carrier: 'Telenor / Telia', network: '5G' },
  'DK': { carrier: 'TDC / Telenor', network: '5G' },
  'FI': { carrier: 'Elisa / DNA', network: '5G' },
  'AT': { carrier: '3 / A1', network: '5G' },
  'IE': { carrier: '3 / Vodafone', network: '5G' },
  'PT': { carrier: 'NOS / MEO', network: '5G' },
  'GR': { carrier: 'Nova / Cosmote', network: '5G' },
  'PL': { carrier: 'Plus', network: '5G' },
  'CZ': { carrier: 'T-Mobile / O2', network: '5G' },
  'HU': { carrier: 'T-Mobile / Yettel', network: '5G' },
  'RO': { carrier: 'Digi / Orange', network: '5G' },
  'BG': { carrier: 'Vivacom / A1', network: '4G/5G' },
  'HR': { carrier: 'Tele2 / A1', network: '4G/5G' },
  'SI': { carrier: 'Telemach / A1', network: '4G/5G' },
  'SK': { carrier: 'T-Mobile / O2', network: '5G' },
  'EE': { carrier: 'Elisa / Telia', network: '5G' },
  'LV': { carrier: 'Bite / Tele2', network: '4G/5G' },
  'LT': { carrier: 'Bite / Telia', network: '4G/5G' },
  'IS': { carrier: 'Vodafone / Nova', network: '4G' },
  'LU': { carrier: 'Tango / Orange', network: '5G' },
  'DZ': { carrier: 'Djezzy', network: '4G' },
  'KH': { carrier: 'Metfone', network: '4G' },
  'MO': { carrier: 'CTM', network: '5G' },
};

export const MOCK_ACTIVE_SIMS: import('./types').ActiveSim[] = [];

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}

export const MOCK_NOTIFICATIONS: import('./types').AppNotification[] = [
  {
    id: 'N-001',
    type: 'data_low',
    titleKey: 'inbox.data_low_title',
    bodyKey: 'inbox.data_low_body_auto',
    date: hoursAgo(2),
    read: false,
    actionLabel: 'inbox.top_up_now',
    countryCode: 'US',
    planName: '0.2 GB / 1.0 GB',
  },
  {
    id: 'N-002',
    type: 'expiring',
    titleKey: 'inbox.expiring_title',
    bodyKey: 'inbox.expiring_body_auto',
    date: hoursAgo(18),
    read: false,
    actionLabel: 'inbox.renew_plan',
    countryCode: 'JP',
    planName: '3',
  },
  {
    id: 'N-003',
    type: 'order',
    titleKey: 'inbox.esim_order_title',
    bodyKey: 'inbox.esim_order_body',
    date: hoursAgo(48),
    read: true,
    actionLabel: 'inbox.install_now',
    countryCode: 'TH',
    planName: 'Thailand 3GB/15Days',
    orderNo: 'ORD-20260307-8832',
  },
  {
    id: 'N-004',
    type: 'promo',
    titleKey: 'inbox.promo_title',
    bodyKey: 'inbox.promo_body',
    date: hoursAgo(120),
    read: true,
    actionLabel: 'inbox.shop_now',
  },
  {
    id: 'N-005',
    type: 'service',
    titleKey: 'inbox.service_title',
    bodyKey: 'inbox.service_body',
    date: hoursAgo(168),
    read: true,
  },
];
