/**
 * Live chat API service.
 *
 * Wraps the `/v1/app/conversations/*` endpoints exposed by the Laravel
 * `ConversationController`. Mirrors the contract documented in
 * `docs/CROSS_PLATFORM_CONTRACT.md` §5.
 *
 *   - `getOrCreateConversation()` — POST /app/conversations. The server
 *     returns the open conversation if one exists, or creates a new one.
 *   - `sendMessage()` — POST /app/conversations/{id}/messages. Always
 *     pass `client_msg_id` (UUID) for optimistic UI dedup; the WS event
 *     carries the same id back so we can reconcile.
 *   - `listMessages()` — GET /app/conversations/{id}/messages. Optional
 *     `since` query param (ISO timestamp) for delta polling fallback.
 *   - `uploadAttachment()` — POST /app/chat/upload (image/pdf, returns URL).
 *
 * Wire format is documented in CROSS_PLATFORM_CONTRACT — keep this file in
 * sync if the doc changes.
 */

import { get, post } from './client';

// ─── Endpoints ──────────────────────────────────────────────────────────

const ENDPOINTS = {
  CONVERSATIONS: '/app/conversations',
  MESSAGES: (conversationId: number | string) =>
    `/app/conversations/${conversationId}/messages`,
  UPLOAD: '/app/chat/upload',
} as const;

// ─── Types ──────────────────────────────────────────────────────────────

export type MessageType = 'text' | 'image' | 'order' | 'product';
export type MessageSender = 'customer' | 'agent' | 'system';

export interface ConversationDto {
  id: number;
  user_id: number;
  status: 'open' | 'needs_agent' | 'resolved' | 'closed';
  language: string;
  customer_name: string | null;
  customer_email: string | null;
  unread_count?: number;
  last_message_at?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface ChatMessageDto {
  id: number;
  conversation_id: number;
  sender: MessageSender;
  sender_name: string | null;
  sender_admin?: { username: string | null; avatar: string | null };
  content: string;
  english_content?: string | null;
  /**
   * Echo of the UUID generated by the client when sending. Used to dedup
   * the optimistic local entry against the server-confirmed message that
   * arrives over the WS. Server may return null for messages it
   * generated (system, agent-side).
   */
  client_msg_id: string | null;
  is_read: boolean;
  message_type: MessageType;
  media_url: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface CreateConversationRequest {
  customer_name?: string;
  customer_email?: string;
  language?: string;
}

export interface SendMessageRequest {
  content: string;
  message_type?: MessageType;
  client_msg_id: string; // required — caller MUST generate a UUID
  sender_name?: string;
  media_url?: string;
  metadata?: Record<string, unknown>;
}

export interface UploadResponse {
  url: string;
  width?: number;
  height?: number;
  bytes?: number;
}

// ─── Helpers ────────────────────────────────────────────────────────────

/**
 * Generate a UUID for the `client_msg_id` field. Uses `crypto.randomUUID`
 * when available (all modern browsers); falls back to a Math.random-based
 * UUID4-shaped string for older Safari versions. Collision-resistant
 * enough for a per-user dedup window.
 */
export function newClientMsgId(): string {
  try {
    if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
      return crypto.randomUUID();
    }
  } catch {
    /* fall through to fallback */
  }

  // Fallback: RFC4122-shaped random string. Not crypto-strong but unique
  // enough for client_msg_id (server only uses it for ~30s dedup window).
  const seg = (n: number) =>
    Math.floor(Math.random() * 16 ** n)
      .toString(16)
      .padStart(n, '0');
  return `${seg(8)}-${seg(4)}-4${seg(3)}-${((Math.random() * 4) | 0 + 8).toString(16)}${seg(3)}-${seg(12)}`;
}

// ─── API methods ────────────────────────────────────────────────────────

export const chatService = {
  /**
   * Get the user's open conversation, or create one if none exists.
   * Idempotent: calling repeatedly returns the same conversation while
   * its status is `open` or `needs_agent`.
   */
  async getOrCreateConversation(
    payload: CreateConversationRequest = {}
  ): Promise<ConversationDto> {
    return await post<ConversationDto>(ENDPOINTS.CONVERSATIONS, payload);
  },

  /**
   * Send a chat message. The `client_msg_id` is the dedup key for the
   * local optimistic entry; the WS broadcast echoes it so the consumer
   * can reconcile (replace optimistic with server-confirmed). Caller is
   * responsible for generating it via `newClientMsgId()`.
   */
  async sendMessage(
    conversationId: number,
    payload: SendMessageRequest
  ): Promise<ChatMessageDto> {
    return await post<ChatMessageDto>(ENDPOINTS.MESSAGES(conversationId), payload);
  },

  /**
   * List messages for the current user's conversation. Pass `since` to
   * receive only messages created strictly after the given ISO timestamp
   * (used by the polling fallback when WS isn't available).
   */
  async listMessages(
    conversationId: number,
    options: { since?: string } = {}
  ): Promise<ChatMessageDto[]> {
    const params = new URLSearchParams();
    if (options.since) params.set('since', options.since);
    const qs = params.toString() ? `?${params.toString()}` : '';
    return await get<ChatMessageDto[]>(`${ENDPOINTS.MESSAGES(conversationId)}${qs}`);
  },

  /**
   * Upload an attachment (image/pdf). Returns the public URL to embed
   * in `media_url` of a subsequent `sendMessage` call.
   *
   * NB: Uses the raw fetch API rather than `client.ts` because the
   * payload is multipart/form-data, not JSON.
   */
  async uploadAttachment(file: File): Promise<UploadResponse> {
    const fd = new FormData();
    fd.append('file', file);

    const baseUrl = (await import('./client')).getBaseUrl();
    const token = (await import('./client')).getAccessToken();

    const response = await fetch(`${baseUrl}${ENDPOINTS.UPLOAD}`, {
      method: 'POST',
      headers: token ? { Authorization: `Bearer ${token}` } : undefined,
      body: fd,
    });

    if (!response.ok) {
      throw new Error(`Upload failed: HTTP ${response.status}`);
    }

    const body = await response.json();
    if (body?.code !== 0 && body?.code !== '200' && body?.code !== '201') {
      throw new Error(body?.msg || 'Upload failed');
    }
    return body.data as UploadResponse;
  },
};

export default chatService;
